name: WDIO-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: ${{secrets.RUNNER}}
      LOG_LEVEL: ${{secrets.LOG_LEVEL}}
      SERVICENOW_ADMIN_USERNAME: ${{secrets.SERVICENOW_ADMIN_USERNAME}}
      SERVICENOW_ADMIN_PASSWORD: ${{secrets.SERVICENOW_ADMIN_PASSWORD}}
    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: npm run test:smoke
